### ISSUE TITLE
Injecting custom directive header

### ISSUE THREAD

**Issue by marc-antoinepelletier** [handsontable/ngHandsontable#125]
Hey,

I have a directive that has a specific template and functionalities that I would like to inject into the header, is there is anyway doing that with the hotColumn directive ?

**Comment by redlive** [comment]
I need same functionality...

**Comment by kotmatpockuh** [comment]
me too...

**Comment by jprince** [comment]
Any of you guys figure this out? I'm trying to do the same. It's unclear how I can call `$compile` without a custom renderer, which I haven't figured out how to use on a header.

**Comment by jlsalmon** [comment]
I managed to get something working with row headers, but it shouldn't be too hard to adapt for column headers. 

Basically I dynamically compile an Angular directive and inject it into the row header. It's a bit complicated (manually compiling and interpolating templates) but it pretty much works.

Here's a fiddle: http://jsfiddle.net/j_lewis/46jckgp3/2/

**Comment by jprince** [comment]
Thanks for the help. I was hoping to avoid using the `afterRender` callback, because I find that it runs a lot on a grid that uses virtual scrolling. I might be able to use your approach with `afterInit` though. Will report back later.

**Comment by marc-antoinepelletier** [comment]
The solution from @jlsalmon is the solution that I was using before I open this issue, unfortunately it create a great loss in performance.. 

To be more precise I was using the afterGetColHeader to recompile the header (also tried with the afterRender) and it wasn't great at all.

At the moment I removed the directive from the header and create another external tool from Handsontable because it's not viable.

The problem is that the numerous of time that Handsontable is re-rendering the entire tend to make it impossible... one way would be that they don't re-render the header every time there is an update in the table but only when you either resize or add/remove a column.

**Comment by jprince** [comment]
@marc-antoinepelletier yea, that's been exactly my experience. I too tried `afterGetColHeader` and found that it was as bad, performance-wise, as `afterRender`. I'm planning to spend some more time on it this afternoon and early next week, as this is a must-have for my implementation. I'll let you know if I have any success.

**Comment by marc-antoinepelletier** [comment]
I also spent half a week on the problem and couldn't find a viable solution without touching handsontable source code. I really do hope that you will find something !

**Comment by jprince** [comment]
Sorry for the super late reply, but I've been pretty busy as of late. I wanted to share the "solution" that I landed on for this. I'm going to preface this by saying that this feels... dirty. So much so that after a bit of investigation my team has decided to move on from Handsontable because of this and performance concerns stemming from the cells function.

In any case, the best solution I came up with, after a couple days of investigation is this:

In the grid settings, use the `colHeaders` function to pass placeholder HTML for each column:
```javascript
getReportHeaders = function(columnNames) {
  $scope.headers = [];
  columnNames.forEach(function(header, i) {
    var columnDef;
    columnDef = {
      colName: header,
      filterText: 'filter'
    };
    return $scope.headers[i] = columnDef;
  });
  return $scope.headers;
};

headers = getReportHeaders(Object.keys(data[0]));

colHeaders: _(headers).map(function(header, i) {
  return "<report-header display-name='" + header.colName + "' index='" + i + "' > </report-header>";
}),
```

Then, after each grid render, find these elements in the DOM, replace their HTML with my "directive" template, compile it on scope, and insert it into the DOM:
```javascript
onAfterRender: function() {
  var gridHeaders;
  gridHeaders = angular.element(document).find('report-header');
  return _(gridHeaders).each(function(gridHeader) {
    var cssClass, displayName, el, html, index;
    displayName = gridHeader.getAttribute('display-name');
    index = gridHeader.getAttribute('index');
    html = "<div> <div>" + displayName + "</div> <div> <input type='text' ng-enter='applyColumnarFilters()' ng-model='headers[" + index + "].filterText' /> </div> </div>";
    el = $compile(html)($scope.$new());
    return gridHeader.appendChild(el[0]);
  });
}
```

This appropriately creates a two-way bind for my ng-model. At this point I ran into issues with my directives not unbinding with each render, which essentially meant I was leaking $$watchers. To address that issue I did the following just before each grid render:
```javascript
onBeforeRender: function() {
  var gridHeaders;
  gridHeaders = angular.element(document).find('report-header');
  return _(gridHeaders).each(function(gridHeader) {
    angular.element(angular.element(gridHeader).find('div')[0]).scope().$destroy();
    return gridHeader.removeChild(gridHeader.firstChild);
  });
}
```

Here's a plunkr - http://jsfiddle.net/jprince/6hfdu2j0/15/

I tested this on a grid with about 80 columns and 200 rows and it performed well, with no visible latency as headers were recompiled and appended after each render.

A couple of things worth noting:
- I first tried, as I'm sure you guys have, to pass a directive to the `colHeaders` function. Unfortunately Handsontable doesn't compile it, so it just renders the HTML without compilation or binding to scope. I played with directive compile and link functions to no avail.
- I then tried replacing the placeholder HTML with a directive (in hopes that I could use its link function to destroy my scopes/bindings when the element was destroyed) in my `afterRender` but again the directive was not compiled or bound to scope.
- I tried, extensively, to use an event other than `afterRender` - I really hoped I could get it to work with `afterInit`, as it only runs once, but I ran into a variety of issues. Not the least of which is needing to re-render the header when scrolling horizontally.

Ultimately this was the output of extensive trial and error. I wish I'd taken notes so that I could better describe the various permutations of my implementation, but rest assured that I tried improving this in just about every way I could think of. Ultimately, the needs of our implementation were such that I wasn't comfortable with this approach (coupled with other performance concerns - perhaps if it were just this one issue we could have lived with it), so we're no longer using Handsontable. Nonetheless I thought I'd share this in hopes that someone finds it useful.

**Comment by jprince** [comment]
I somehow only just looked closely at @jlsalmon's approach above (::facepalm::) and it looks like our approaches are very similar (though he seems to have had success using the directive in the `afterRender`, where I struggled to do so), so it's unlikely that the above code will be terribly useful. Good luck nonetheless.

**Comment by marc-antoinepelletier** [comment]
Thank you for coming back with your investigation @jprince I had the same result as you had. Although I haven't try to recompile the template the header with the `onAfterRenderer` and `onBeforeRenderer`. The main issue for me was the render on scrolling which is a complete non sense in my opinion.

I will try to give it another shot at it.

@jprince do you mind sharing your alternative solution for Handsontable ?

**Comment by jprince** [comment]
@marc-antoinepelletier [ag-grid](https://www.ag-grid.com/). It's interface is very much like ng-grid/ui-grid which is the library we were previously using and are now moving away from because of serious performance issues. The author has a great [blog post ](https://www.ag-grid.com/why-the-world-needed-another-angularjs-grid/) describing his experiences which resulted in him developing his own library. His frustrations were very similar to those of our team, and from our initial POC the performance is quite good (on par with handsontable) while giving us the amount of configurability that we need.

**Comment by AMBudnik** [comment]
I think that we can close this issue as it hasn't been updated for a long time.
