### ISSUE TITLE
How to make handsontable stretch to full width of parent container

### ISSUE THREAD

**Issue by cheahkhing** [handsontable/ngHandsontable#126]
I tried various solutions, even with custom className and stretchH to 'all'.
It doesn't work properly when i resize my browser window. :(

Anyone have idea how to make them resize accordingly even after browser resize?

**Comment by AMBudnik** [comment]
Hi `stretchH` should work with window resizing, like in [this demo](http://jsbin.com/lulixawiji/1/edit?js,output). Can you create a demo with your code? Maybe something is blocking this option.

**Comment by cheahkhing** [comment]
I think i found out the root cause of the issue, it is due to bootstrap "collapse" directive on parent div that causes it to behave wrongly. Basically hot-table just doesn't work properly if parent contains bootstrap "collapse" directive.

**Comment by GeekRoot999** [comment]
Hi guys,
 I am also facing a similar issue. The handsonTable we are using is of version 2.0.0. Due to some reason we cant update it to the latest version. In my case, it is accepting both width: 100% and stretchH to "all". but when I give this property. I am not able to select the table td cell. When I remove the width property I am able to select the table td cell. 
My actual question is what would be the problem? Even If I remove width 100%, Is there any alternative way to make the table fluid and fitting to parent width.
I tried many ways to fix this issue but dint find anything. 
Could anyone suggest me any possible solution to this problem?
