### ISSUE TITLE
slow/freeze on horizontal scroll

### ISSUE THREAD

**Issue by jumpei-yamauchi** [handsontable/ngHandsontable#164]
Hi,

We have set up a grid with over 40 columns and expect to retrieve 250-300 entries in the grid.

Noticed that horizontal scroll bar becomes slow and freeze for while when trying to scroll to the right.

There are custom formatting applied in the cells and they have been removed and also moved all the columns definition from html to the setting object but still seeing the same issue. 

Are there any other configuration changes or else to improve the performance of the grid?

Thank you for your cooperation,

**Comment by murph1329** [comment]
I'll try to give you a code example sometime this week.  But for now i would look into "limitTo"

You'll want to use this on your column and data objects in order to "take" a certain number of items.  You can drive the behavior off a parameter and implement virtual scrolling behavior or drive it off a "show more" button click.
