### ISSUE TITLE
how to activate the search plugin?

### ISSUE THREAD

**Issue by xmamat** [handsontable/ngHandsontable#60]
Hello,

I couldn't find how to activate the search plugin of Handsontable. Setting `search: true` in ngHandsontable `hot-table` declaration doesn't help since this option doesn't belong to `Handsontable.DefaultSettings` keys or `Handsontable.PluginHooks`.

The only workaround I found is to add a `settings.search=true;` line in the `setHandsontableSettingsFromScope` function.

Thanks.

**Comment by davidgeary** [comment]
This problem appears to affect all plugins.

The [`settingFactory.setHandsontableSettingsFromScope`](https://github.com/handsontable/ngHandsontable/blob/master/src/services/settingFactory.js#L63) method is explicitly checking for the existence of each setting before assigning the values to it and since plugin settings are not included in the default grid settings, they are being ignored.

Looks like it possibly needs a change in the main grid component to include these or at least allow them to be 'registered' by each plugin.

**Comment by epernice** [comment]
+1

**Comment by omayhemo** [comment]
+1

Everytime I turn around ngHoT is missing something.  I'm regretting pulling this into my project.
epernice, can you elaborate on your work around?  I'm not having any success enabling search.

**Comment by AMBudnik** [comment]
I think that we can close this issue as it hasn't been updated for a long time.
