### ISSUE TITLE
IE: Unable to get property 'length' of undefined or null reference.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/ngHandsontable#66]
alexandergs commented 19 hours ago
>I am getting this error in IE, but not in Chrome:

>"Unable to get property 'length' of undefined or null reference."

>The error also shows in their demo page. You can F12 to see the error as you simply moves the mouse:

>http://handsontable.github.io/ngHandsontable/

source: https://github.com/handsontable/handsontable/issues/2437

**Comment by alexandergs** [comment]
How do I see the code changes that fixed this?

**Comment by AMBudnik** [comment]
Issue is not closed yet, it will be closed with a fix - which is a new release. I cannot guarantee when it will happen, but please follow this issue to stay tunned.

**Comment by alexandergs** [comment]
Is it possible you can share how to fix it locally? :) Meanwhile the fix is released?

Maybe you can provide more details on the issue here:

http://stackoverflow.com/questions/30041603/handsontable-0-14-1-nghandsontable-0-5-2-unable-to-get-property-length-of-u

This way you would be helping me with getting reputation and then I will be able to answer questions myself. Right now I cannot since I don't have enough reputation.

That would be SO appreciated!

**Comment by budnix** [comment]
Released in 0.6.0
